#!/usr/bin/env bash
# Copyright 2021 Borting Chen <bortingchen@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Change the kernel release you attempt to present here. For example,
# FAKE_KERNEL_RELEASE="4.15.0-112-generic"
FAKE_KERNEL_RELEASE=`/bin/uname -r`

# Reset in case getopts has been used previously in the shell.
OPTIND=1

if [ $# -eq 0 ]; then
	/bin/uname
else
	while getopts "asnrvmpio" opt; do
		case "$opt" in
			r)
				echo ${FAKE_KERNEL_RELEASE}
				;;
			*)
				/bin/uname -$opt
				;;
		esac
	done
fi

